'use strict';
// const nav = document.querySelector('.nav_open');

// const btnclose = document.querySelector('.icon_close');
// const btnopen = document.querySelector('.icon_open');

// btnopen.addEventListener('click', function (e) {
//   e.preventDefault();
//   nav.classList.add('nav_open');
// });
// btnclose.addEventListener('click', function (e) {
//   e.preventDefault();
//   nav.classList.remove('nav_open');
// });
